# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YFMediator' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

#  # Pods for YFMediator
pod 'YFMediatorService', :path => '../YFMediatorService'
pod 'YFSendModule’, :path => '../YFSendModule'
pod 'YFReceiveModule’, :path => '../YFReceiveModule'
pod 'SnapKit'

end
